deployment:
  nexus:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nexus
      labels:
        app: nexus
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nexus
      template:
        metadata:
          labels:
            app: nexus
        spec:
          containers:
            - name: nexus
              image: sonatype/nexus3:latest
              ports:
                - containerPort: 8081
              env:
                - name: POSTGRES_DB
                  value: nexusdb
                - name: POSTGRES_USER
                  value: nexus
                - name: POSTGRES_PASSWORD
                  value: nexuspassword
              volumeMounts:
                - name: nexus-data
                  mountPath: "/mnt/data/nexus"
          volumes:
            - name: nexus-data
              persistentVolumeClaim:
                claimName: nexus-pvc
