postgresql:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgresql
      labels:
        app: postgresql
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgresql
      template:
        metadata:
          labels:
            app: postgresql
        spec:
          containers:
            - name: postgresql
              image: postgres:15
              ports:
                - containerPort: 5432
              env:
                - name: POSTGRES_DB
                  value: nexusdb
                - name: POSTGRES_USER
                  value: nexus
                - name: POSTGRES_PASSWORD
                  value: nexuspassword
              volumeMounts:
                - name: postgresql-data
                  mountPath: "/mnt/data/postgresql"
          volumes:
            - name: postgresql-data
              persistentVolumeClaim:
                claimName: postgresql-pvc
