apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  storageClassName: standard
  capacity:
    storage: {{ .Values.nexus.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nexus"
