apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  storageClassName: standard
  capacity:
    storage: {{ .Values.postgresql.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgresql"
